### ISSUE TITLE
problem with type object subscriptability?

### ISSUE THREAD

**Issue by joelgroves** [vdbg/hubibtpresence#5]
Not sure how to resolve this issue?

python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from hubitat import Hubitat
  File "/home/Joel/Documents/hubibtpresence/hubibtpresence/hubitat.py", line 13, in <module>
    class Hubitat:
  File "/home/Joel/Documents/hubibtpresence/hubibtpresence/hubitat.py", line 20, in Hubitat
    def get_all_devices(self) -> dict[int, Device]:
TypeError: 'type' object is not subscriptable

EDIT: Eek, should have correctly read the minimum Python version is 3.9.0 (my tired eyes saw this as 3.8.0).

**Comment by nmedveditskov-salesforce** [comment]
Yep, that's a wrong python version issue.  @vdbg , consider checking python version on the script startup.

**Comment by vdbg** [comment]
Sorry for that; will add some code to fail with proper error msg
